# Generated by Django 5.0.6 on 2026-08-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, help_text="Card number/order (e.g., '01', '02')", max_length=10, null=True)),
                ('heading', models.CharField(blank=True, help_text='Project title', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Project description', null=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-microchip')", max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Project image', null=True, upload_to='projects/')),
                ('points', models.TextField(blank=True, help_text='Enter each point separated by newline', null=True)),
                ('technologies', models.TextField(blank=True, help_text='Enter each technology separated by newline', null=True)),
                ('key_results', models.TextField(blank=True, help_text='Enter each result separated by newline', null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('project_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectsection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
