# Generated by Django 6.1 on 2026-08-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('solver_used', models.CharField(blank=True, max_length=255)),
                ('workflow_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('location', models.CharField(choices=[('nav', 'Navigation'), ('footer', 'Footer')], default='nav', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Divergent Physics', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('calendar_link', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('problem', 'Problem Framing'), ('stats', 'Stats'), ('field_notes', 'Field Notes'), ('services', 'Services'), ('case_study', 'Case Study'), ('assets', 'Assets'), ('how_we_work', 'How We Work'), ('why_us', 'Why Us'), ('demo', 'Demonstration'), ('faq', 'FAQ'), ('cta', 'CTA'), ('about', 'About / Team'), ('logos', 'Company Logos'), ('custom', 'Custom')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('subheading', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('video_url', models.URLField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='website.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_items/')),
                ('link', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
