# Generated by Django 5.0.6 on 2026-08-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(blank=True, default='Divergent Physics', max_length=200, null=True)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Main site logo (upload image)', null=True, upload_to='settings/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Dark version of logo for light backgrounds', null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (upload image)', null=True, upload_to='settings/')),
                ('email', models.EmailField(blank=True, help_text='General contact email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical address or location', max_length=500, null=True)),
                ('footer_description', models.TextField(blank=True, help_text='Footer description text', null=True)),
                ('copyright_text', models.CharField(blank=True, default='© 2024 Divergent Physics. All rights reserved.', max_length=200, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X URL', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('github', models.URLField(blank=True, help_text='GitHub URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube URL', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='TikTok URL', null=True)),
                ('calendar_link', models.URLField(blank=True, help_text='Booking/calendar link (e.g., Calendly)', null=True)),
                ('contact_form_cta', models.CharField(blank=True, default='Book a Consultation →', max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
