# Generated by Django 5.0.6 on 2026-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, help_text="e.g., '5 min read'", max_length=50, null=True),
        ),
    ]
