# Generated by Django 5.0.6 on 2026-08-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatingBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, help_text="Impact statement (e.g., 'Faster evaluation of design alternatives')", max_length=200, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform/benefits/')),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_benefits', to='platformm.platformsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demonstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='platform/demos/')),
                ('cta_label', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonstrations', to='platformm.platformsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform/coming-soon/')),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_soon', to='platformm.platformsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuiltForProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform/production/')),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_for_production', to='platformm.platformsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text="Plan name (e.g., 'Professional', 'Enterprise')", max_length=100, null=True)),
                ('price', models.CharField(blank=True, help_text="Price (e.g., '$400 PER MONTH', 'Custom Pricing')", max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('what_included', models.TextField(blank=True, help_text='Enter each included feature separated by newline', null=True)),
                ('best_for', models.CharField(blank=True, help_text="Best for (e.g., 'Individuals & Small Teams')", max_length=200, null=True)),
                ('cta_label', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight as featured plan')),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='platformm.platformsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, help_text="Card title (e.g., 'Agents', 'Services')", max_length=100, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform/work/')),
                ('cta_label', models.CharField(blank=True, help_text='Call to action label', max_length=100, null=True)),
                ('cta_link', models.URLField(blank=True, help_text='Call to action link', null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_with_us', to='platformm.platformsection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
