# Generated by Django 5.0.6 on 2026-08-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100, null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.aboutsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('patent_number', models.CharField(blank=True, max_length=100, null=True)),
                ('inventors', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='about.aboutsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, help_text='Full citation in APA/MLA format', null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='about.aboutsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, help_text='e.g., PhD, RF Engineer', max_length=200, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Co-Founder, Lead Engineer', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Team member bio/description', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about.aboutsection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
